export const projects = [
    {
        id: "brand-identity",
        title: "Lumina Branding",
        category: "Branding",
        color: "bg-blue-500",
        description: "A complete brand identity overhaul for a tech startup.",
        fullDescription: "Lumina is a cutting-edge tech startup focused on renewable energy solutions. The goal was to create a brand identity that reflects innovation, sustainability, and trust. We developed a clean, modern logo, a vibrant color palette, and a comprehensive brand guideline.",
        images: ["/placeholder-1.jpg", "/placeholder-2.jpg"], // Placeholders
        client: "Lumina Tech",
        timeline: "4 Weeks",
        role: "Brand Designer",
    },
    {
        id: "mobile-app",
        title: "FitTrack App",
        category: "UI/UX",
        color: "bg-purple-500",
        description: "Fitness tracking application with social features.",
        fullDescription: "FitTrack is a mobile application designed to help users track their fitness journey and connect with a community. The UI focuses on simplicity and motivation, using bright colors and intuitive navigation.",
        images: ["/placeholder-3.jpg", "/placeholder-4.jpg"],
        client: "FitTrack Inc.",
        timeline: "8 Weeks",
        role: "UI/UX Designer",
    },
    {
        id: "poster-design",
        title: "Jazz Festival",
        category: "Print",
        color: "bg-orange-500",
        description: "Event promotional materials and poster series.",
        fullDescription: "A series of posters for the annual City Jazz Festival. The design uses typography and abstract shapes to visualize the rhythm and energy of jazz music.",
        images: ["/placeholder-5.jpg", "/placeholder-6.jpg"],
        client: "City Arts Council",
        timeline: "2 Weeks",
        role: "Graphic Designer",
    },
    {
        id: "web-layout",
        title: "Architecture Firm",
        category: "Web Design",
        color: "bg-green-500",
        description: "Minimalist portfolio website for architects.",
        fullDescription: "A portfolio website for a high-end architecture firm. The design is minimal and image-focused, allowing the architectural work to take center stage.",
        images: ["/placeholder-7.jpg", "/placeholder-8.jpg"],
        client: "Modern Arch",
        timeline: "6 Weeks",
        role: "Web Designer",
    },
];
